//! Golden tests de `parse_mcps` (nativo → canónico) con fixtures fieles a los
//! formatos reales de cada agente.

use std::collections::BTreeMap;

use nodify_adapters::{ClaudeAdapter, CodexAdapter, OpenCodeAdapter};
use nodify_core::{Adapter, SecretValue, Transport};

fn env(pairs: &[(&str, &str)]) -> BTreeMap<String, SecretValue> {
    pairs
        .iter()
        .map(|(k, v)| (k.to_string(), SecretValue::Inline(v.to_string())))
        .collect()
}

// ---------- Claude Code ----------

#[test]
fn claude_parses_stdio_http_and_sse() {
    let raw = r#"{
      "oauthAccount": { "keep": "me" },
      "mcpServers": {
        "codegraph": { "type": "stdio", "command": "codegraph", "args": ["serve", "--mcp"] },
        "docs": { "type": "http", "url": "https://x/mcp", "headers": { "Authorization": "Bearer abc123xyz" } },
        "sentry": { "type": "sse", "url": "https://mcp.sentry.dev/mcp" }
      }
    }"#;

    let mcps = ClaudeAdapter.parse_mcps(raw).unwrap();
    assert_eq!(mcps.len(), 3);

    // orden alfabético
    let codegraph = &mcps[0];
    assert_eq!(codegraph.name, "codegraph");
    assert_eq!(codegraph.transport, Transport::Stdio);
    assert_eq!(codegraph.command.as_deref(), Some("codegraph"));
    assert_eq!(codegraph.args, vec!["serve", "--mcp"]);
    assert_eq!(codegraph.enabled, None); // Claude no tiene flag nativo

    let docs = &mcps[1];
    assert_eq!(docs.transport, Transport::Http);
    assert_eq!(docs.url.as_deref(), Some("https://x/mcp"));
    assert_eq!(
        docs.headers.get("Authorization"),
        Some(&SecretValue::Inline("Bearer abc123xyz".into()))
    );

    let sentry = &mcps[2];
    assert_eq!(sentry.transport, Transport::Http);
    assert_eq!(sentry.extras, serde_json::json!({ "claudeType": "sse" }));
}

#[test]
fn claude_without_mcp_servers_is_empty() {
    assert!(ClaudeAdapter
        .parse_mcps(r#"{"foo": 1}"#)
        .unwrap()
        .is_empty());
}

#[test]
fn claude_stdio_without_command_errors() {
    let raw = r#"{ "mcpServers": { "bad": { "type": "stdio" } } }"#;
    assert!(ClaudeAdapter.parse_mcps(raw).is_err());
}

// ---------- OpenCode ----------

#[test]
fn opencode_parses_remote_and_normalizes_command_forms() {
    // Incluye comentarios (JSONC) y las dos formas de `command`:
    // array oficial (codegraph) y string+args+env no estándar (firecrawl).
    let raw = r#"{
      // generated by opencode-synced
      "mcp": {
        "context7": { "type": "remote", "url": "https://mcp.context7.com/mcp", "enabled": true },
        "codegraph": { "type": "local", "command": ["codegraph", "serve", "--mcp"] },
        "firecrawl-mcp": {
          "type": "local",
          "command": "npx",
          "args": ["-y", "firecrawl-mcp"],
          "env": { "FIRECRAWL_API_KEY": "fc-secret-401a" },
          "enabled": true,
        },
      },
    }"#;

    let mcps = OpenCodeAdapter.parse_mcps(raw).unwrap();
    assert_eq!(mcps.len(), 3);

    let codegraph = mcps.iter().find(|m| m.name == "codegraph").unwrap();
    assert_eq!(codegraph.transport, Transport::Stdio);
    assert_eq!(codegraph.command.as_deref(), Some("codegraph"));
    assert_eq!(codegraph.args, vec!["serve", "--mcp"]);

    let firecrawl = mcps.iter().find(|m| m.name == "firecrawl-mcp").unwrap();
    assert_eq!(firecrawl.command.as_deref(), Some("npx"));
    assert_eq!(firecrawl.args, vec!["-y", "firecrawl-mcp"]);
    assert_eq!(
        firecrawl.env,
        env(&[("FIRECRAWL_API_KEY", "fc-secret-401a")])
    );
    assert_eq!(firecrawl.enabled, Some(true));

    let context7 = mcps.iter().find(|m| m.name == "context7").unwrap();
    assert_eq!(context7.transport, Transport::Http);
    assert_eq!(
        context7.url.as_deref(),
        Some("https://mcp.context7.com/mcp")
    );
    assert_eq!(context7.enabled, Some(true));
}

// ---------- Codex ----------

#[test]
fn codex_parses_stdio_and_http_with_bearer_ref() {
    let raw = r#"
        [mcp_servers.context7]
        command = "npx"
        args = ["-y", "@upstash/context7-mcp"]
        env = { API_KEY = "inline-value" }
        enabled = true
        startup_timeout_sec = 10

        [mcp_servers.figma]
        url = "https://mcp.figma.com/mcp"
        bearer_token_env_var = "FIGMA_OAUTH_TOKEN"
    "#;

    let mcps = CodexAdapter.parse_mcps(raw).unwrap();
    assert_eq!(mcps.len(), 2);

    let context7 = mcps.iter().find(|m| m.name == "context7").unwrap();
    assert_eq!(context7.transport, Transport::Stdio);
    assert_eq!(context7.command.as_deref(), Some("npx"));
    assert_eq!(context7.args, vec!["-y", "@upstash/context7-mcp"]);
    assert_eq!(context7.env, env(&[("API_KEY", "inline-value")]));
    assert_eq!(context7.enabled, Some(true));
    assert_eq!(context7.timeout_ms, Some(10_000)); // segundos → ms

    let figma = mcps.iter().find(|m| m.name == "figma").unwrap();
    assert_eq!(figma.transport, Transport::Http);
    // bearer_token_env_var → header Authorization por referencia a env var
    assert_eq!(
        figma.headers.get("Authorization"),
        Some(&SecretValue::EnvRef("FIGMA_OAUTH_TOKEN".into()))
    );
}
