//! Golden tests de escritura (canónico → nativo): upsert/remove deben preservar todo
//! lo que no gestionan (ADR-0005) y hacer round-trip con `parse_mcps`.

use std::collections::BTreeMap;

use nodify_adapters::{ClaudeAdapter, CodexAdapter, KiloCodeAdapter, OpenCodeAdapter, PiAdapter};
use nodify_core::mcp::Transport;
use nodify_core::{Adapter, CanonicalMcp, SecretValue};

fn stdio(name: &str, cmd: &str, args: &[&str]) -> CanonicalMcp {
    let mut m = CanonicalMcp::stdio(name, cmd);
    m.args = args.iter().map(|s| s.to_string()).collect();
    m
}

// ---------- Claude ----------

#[test]
fn claude_upsert_preserves_unknown_top_level_keys() {
    let raw = r#"{
  "oauthAccount": { "keep": "me" },
  "userID": "abc-123",
  "mcpServers": {
    "existing": { "type": "stdio", "command": "old" }
  }
}"#;

    let out = ClaudeAdapter
        .upsert_mcp(raw, &stdio("github", "npx", &["-y", "gh-mcp"]))
        .unwrap();

    // preserva estado de máquina
    assert!(out.contains("oauthAccount"));
    assert!(out.contains("\"userID\""));
    assert!(out.contains("abc-123"));
    // conserva el MCP previo y añade el nuevo
    let mcps = ClaudeAdapter.parse_mcps(&out).unwrap();
    let names: Vec<_> = mcps.iter().map(|m| m.name.as_str()).collect();
    assert!(names.contains(&"existing"));
    assert!(names.contains(&"github"));
    let gh = mcps.iter().find(|m| m.name == "github").unwrap();
    assert_eq!(gh.command.as_deref(), Some("npx"));
    assert_eq!(gh.args, vec!["-y", "gh-mcp"]);
}

#[test]
fn claude_upsert_into_empty_file_creates_structure() {
    let out = ClaudeAdapter
        .upsert_mcp("", &stdio("fs", "npx", &["@mcp/fs"]))
        .unwrap();
    let mcps = ClaudeAdapter.parse_mcps(&out).unwrap();
    assert_eq!(mcps.len(), 1);
    assert_eq!(mcps[0].name, "fs");
}

#[test]
fn claude_remove_is_idempotent_and_keeps_others() {
    let raw = r#"{ "mcpServers": { "a": { "type": "stdio", "command": "x" }, "b": { "type": "stdio", "command": "y" } } }"#;
    let out = ClaudeAdapter.remove_mcp(raw, "a").unwrap();
    let mcps = ClaudeAdapter.parse_mcps(&out).unwrap();
    assert_eq!(
        mcps.iter().map(|m| m.name.as_str()).collect::<Vec<_>>(),
        vec!["b"]
    );
    // quitar algo inexistente no rompe
    let out2 = ClaudeAdapter.remove_mcp(&out, "zzz").unwrap();
    assert_eq!(ClaudeAdapter.parse_mcps(&out2).unwrap().len(), 1);
}

// ---------- Codex ----------

#[test]
fn codex_upsert_preserves_comments_and_other_tables() {
    let raw = r#"# comentario importante
model = "gpt-5.5"

[model_providers.openrouter]
base_url = "https://openrouter.ai/api/v1"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
"#;

    let mut figma = CanonicalMcp::http("figma", "https://mcp.figma.com/mcp");
    figma.headers.insert(
        "Authorization".into(),
        SecretValue::EnvRef("FIGMA_TOKEN".into()),
    );

    let out = CodexAdapter.upsert_mcp(raw, &figma).unwrap();

    // toml_edit preserva comentario, model y la tabla de proveedores
    assert!(out.contains("# comentario importante"));
    assert!(out.contains("model = \"gpt-5.5\""));
    assert!(out.contains("[model_providers.openrouter]"));
    // el nuevo MCP se escribe con bearer_token_env_var (referencia)
    assert!(out.contains("bearer_token_env_var = \"FIGMA_TOKEN\""));

    let mcps = CodexAdapter.parse_mcps(&out).unwrap();
    let names: Vec<_> = mcps.iter().map(|m| m.name.as_str()).collect();
    assert!(names.contains(&"context7"));
    assert!(names.contains(&"figma"));
    let f = mcps.iter().find(|m| m.name == "figma").unwrap();
    assert_eq!(f.transport, Transport::Http);
    assert_eq!(
        f.headers.get("Authorization"),
        Some(&SecretValue::EnvRef("FIGMA_TOKEN".into()))
    );
}

#[test]
fn codex_stdio_roundtrip_with_env_and_timeout() {
    let mut m = stdio("pg", "pg-mcp", &["--port", "5432"]);
    m.env
        .insert("PG_URL".into(), SecretValue::Inline("postgres://x".into()));
    m.timeout_ms = Some(15_000);

    let out = CodexAdapter.upsert_mcp("", &m).unwrap();
    let back = CodexAdapter.parse_mcps(&out).unwrap();
    assert_eq!(back.len(), 1);
    let r = &back[0];
    assert_eq!(r.command.as_deref(), Some("pg-mcp"));
    assert_eq!(r.args, vec!["--port", "5432"]);
    assert_eq!(r.timeout_ms, Some(15_000)); // 15s → ms round-trip
    assert_eq!(
        r.env.get("PG_URL"),
        Some(&SecretValue::Inline("postgres://x".into()))
    );
}

// ---------- OpenCode ----------

#[test]
fn opencode_upsert_preserves_comments_and_other_keys() {
    let raw = r#"{
  // generated by opencode-synced
  "$schema": "https://opencode.ai/config.json",
  "model": "anthropic/claude-sonnet-4",
  "mcp": {
    "context7": { "type": "remote", "url": "https://mcp.context7.com/mcp", "enabled": true }
  }
}"#;

    let out = OpenCodeAdapter
        .upsert_mcp(raw, &stdio("fs", "npx", &["-y", "@mcp/fs"]))
        .unwrap();

    // preserva comentario, $schema y model (splice del bloque mcp)
    assert!(out.contains("// generated by opencode-synced"));
    assert!(out.contains("\"$schema\""));
    assert!(out.contains("anthropic/claude-sonnet-4"));

    let mcps = OpenCodeAdapter.parse_mcps(&out).unwrap();
    let names: Vec<_> = mcps.iter().map(|m| m.name.as_str()).collect();
    assert!(names.contains(&"context7"));
    assert!(names.contains(&"fs"));
    // command se escribe como array (forma oficial OpenCode)
    let fs = mcps.iter().find(|m| m.name == "fs").unwrap();
    assert_eq!(fs.transport, Transport::Stdio);
    assert_eq!(fs.command.as_deref(), Some("npx"));
    assert_eq!(fs.args, vec!["-y", "@mcp/fs"]);
}

#[test]
fn opencode_env_becomes_environment_on_write() {
    let mut m = stdio("fire", "npx", &["-y", "firecrawl-mcp"]);
    m.env.insert(
        "FIRECRAWL_API_KEY".into(),
        SecretValue::Inline("fc-x".into()),
    );
    let out = OpenCodeAdapter.upsert_mcp("", &m).unwrap();
    // campo oficial es `environment`, no `env`
    assert!(out.contains("\"environment\""));
    let back = OpenCodeAdapter.parse_mcps(&out).unwrap();
    let map: BTreeMap<_, _> = back[0].env.clone().into_iter().collect();
    assert_eq!(
        map.get("FIRECRAWL_API_KEY"),
        Some(&SecretValue::Inline("fc-x".into()))
    );
}

// ---------- Kilo Code ----------

#[test]
fn kilo_upsert_preserves_comments_and_model() {
    let raw = r#"{
  // kilo global config
  "model": "anthropic/claude-sonnet-4",
  "mcp": {
    "docs": { "type": "remote", "url": "https://x/mcp" }
  }
}"#;

    let out = KiloCodeAdapter
        .upsert_mcp(raw, &stdio("fs", "npx", &["-y", "@mcp/fs"]))
        .unwrap();

    // splice del bloque mcp: conserva comentario y model
    assert!(out.contains("// kilo global config"));
    assert!(out.contains("anthropic/claude-sonnet-4"));
    // command se escribe como array (forma oficial Kilo)
    assert!(out.contains("\"command\""));

    let mcps = KiloCodeAdapter.parse_mcps(&out).unwrap();
    let names: Vec<_> = mcps.iter().map(|m| m.name.as_str()).collect();
    assert!(names.contains(&"docs"));
    assert!(names.contains(&"fs"));
    let fs = mcps.iter().find(|m| m.name == "fs").unwrap();
    assert_eq!(fs.command.as_deref(), Some("npx"));
    assert_eq!(fs.args, vec!["-y", "@mcp/fs"]);
}

#[test]
fn kilo_remove_is_idempotent() {
    let raw = r#"{ "mcp": { "a": { "type": "local", "command": ["x"] } } }"#;
    let out = KiloCodeAdapter.remove_mcp(raw, "a").unwrap();
    assert!(KiloCodeAdapter.parse_mcps(&out).unwrap().is_empty());
    // quitar inexistente devuelve el texto sin cambios
    assert_eq!(KiloCodeAdapter.remove_mcp(raw, "zzz").unwrap(), raw);
}

// ---------- Pi ----------

#[test]
fn pi_upsert_preserves_settings_and_roundtrips() {
    let raw = r#"{
  "$schema": "https://pi.dev/schema.json",
  "settings": { "toolPrefix": "mcp" },
  "mcpServers": {
    "existing": { "command": "old" }
  }
}"#;

    let mut m = stdio("fs", "npx", &["-y", "@mcp/fs"]);
    m.env
        .insert("ROOT".into(), SecretValue::Inline("/tmp".into()));
    let out = PiAdapter.upsert_mcp(raw, &m).unwrap();

    // preserva claves de nivel superior ajenas a mcpServers
    assert!(out.contains("$schema"));
    assert!(out.contains("toolPrefix"));

    let mcps = PiAdapter.parse_mcps(&out).unwrap();
    let names: Vec<_> = mcps.iter().map(|m| m.name.as_str()).collect();
    assert!(names.contains(&"existing"));
    assert!(names.contains(&"fs"));
    let fs = mcps.iter().find(|m| m.name == "fs").unwrap();
    assert_eq!(fs.transport, Transport::Stdio);
    assert_eq!(
        fs.env.get("ROOT"),
        Some(&SecretValue::Inline("/tmp".into()))
    );
}

#[test]
fn pi_http_upsert_writes_type_and_url() {
    let mut m = CanonicalMcp::http("docs", "https://x/mcp");
    m.headers.insert(
        "Authorization".into(),
        SecretValue::Inline("Bearer z".into()),
    );
    let out = PiAdapter.upsert_mcp("", &m).unwrap();
    assert!(out.contains("\"type\": \"http\""));
    assert!(out.contains("https://x/mcp"));

    let back = PiAdapter.parse_mcps(&out).unwrap();
    assert_eq!(back[0].transport, Transport::Http);
    assert_eq!(
        back[0].headers.get("Authorization"),
        Some(&SecretValue::Inline("Bearer z".into()))
    );
}
